### ISSUE TITLE
Phase 1: Find home base

### ISSUE THREAD

**Issue by omelkonian** [omelkonian/battlecode-2017#1]
- Essentially find our map quarter (i.e. two channels on the message array - indices [0,1]):
     - (1, 1) -> NW
     - (1, 2) -> NE
     - (2, 1) -> SW
     - (2, 2) -> SE
 - Roles:
     - Scouts: Just explore to fill these bits 
     - Gardeners: Explore safely, while shaking trees, building, planting, etc...
     - Archon: Explore very safely and keep track of produced units (e.g. message indices [10-20])

**Comment by DimopoulosGrigorios** [comment]
just explore, explore safely and explore very safely. Should be three different modes on the path finding function. I would recoment to implement all the three of them.

**Comment by omelkonian** [comment]
Pathfinding should not include the concept of safety (for now at least). It should just find nice paths towards some direction. Safety will be a concern of the caller, as he will decide when to stop moving, change direction, etc...

**Comment by omelkonian** [comment]
Maybe a terminating criterion would be helpful in the pathfinding API (e.g. for functionality, terminate if you find map corner or for safety, terminate if #enemies > 3)

**Comment by DimopoulosGrigorios** [comment]
So all the units will move the same way. So safely, very safely etc. does not have any meaning for now.

**Comment by omelkonian** [comment]
No, it has very critical meaning. We do not want the Archon for example to venture too far, thus he has to be ultra-conservative. The Scout on the other hand can fly wherever he wants to.

**Comment by DimopoulosGrigorios** [comment]
Aha, ok with this meaning , I agree!

**Comment by NikitasKotsolakos** [comment]
It is not described here, but as we said we will also produce a soldier / tank (whatever is more effective) for defense? Or we will only start doing this in phase 2?
And if yes, their role should be also to explore, and then on phase 2 they will go defend the place we are building the base, or should they stay near archon / someone and defend from the beginning?

**Comment by DimopoulosGrigorios** [comment]
It is more logic to have the quarters as below:
(1, 1) -> SW
(1, 2) -> NW
(2, 1) -> SE
(2, 2) -> NE
